name = "quack-quack-api"
main = "src/index.ts"
compatibility_date = "2024-05-13"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "HonkRoom" },
  { name = "LEADERBOARDS", class_name = "Leaderboard" },
  { name = "SOUNDS", class_name = "Sounds" },
]

[[r2_buckets]]
binding = 'SOUNDS_BUCKET'
bucket_name = 'quack-quack-sounds'

[[migrations]]
tag = "v1"
new_classes = ["HonkRoom"]

[[migrations]]
tag = "v2"
new_classes = ["Leaderboard"]

[[migrations]]
tag = "v3"
new_classes = ["Sounds"]
